### ISSUE TITLE
Plugin settings

### ISSUE THREAD

**Issue by LeafyLappa** [meanmail-dev/prettify-python-plugin#7]
**Is your feature request related to a problem? Please describe.**
Typeface I'm using provides most of what this plugin does (ligatures). It does not however replace lambda definitions with the lambda character!

**Describe the solution you'd like**
If possible, I'd love to be able to manually choose what gets folded via plugin settings.

**Comment by meanmail** [comment]
Thank you for your feature request! 🙌

Great news - we've implemented the ability to customize replacements in the plugin settings. The update will be available in the next version, which will be released in the coming days.

In the new version, you'll be able to:
- Enable/disable specific replacements
- Add custom replacements
- Edit existing ones
- Organize them by categories

This should perfectly solve your use case with font ligatures - you'll be able to keep only the lambda replacement while disabling the others that your font already provides.

Thanks for helping us improve the plugin! 🚀
